version: '2'
services:
    backend-v1:
      build:
          context: ./
      ports:
          - "10:5000"
      volumes:
          - ./:/code
      restart: always
      environment:
        - LISTEN_PORT=5000
        - UWSGI_INI=/code/uwsgi/uwsgi.ini
        - PYTHONPATH=/code/app
      env_file:
        - ./config.env
      
